### PR TITLE
Added conditional resolution

### PR DESCRIPTION
**Pull request by jschwertfeger**
Sometimes it is necessary to condition resolution of an argument on its value. For instance, by default an empty string as an argument matches only records whose corresponding field is an empty string as well.

However, you may want an empty argument to mean that this argument should be ignored and all records shall be matched. To achieve this, you would condition resolution of that argument on it being not empty.
    
You can condition resolution by passing the `:if` or `:unless` option to the `resolve` method. This option can take a method name (as a symbol or a string), or a `Proc` (or lambda expression for that matter), which will be called with the argument's value.

### CODE REVIEW

**Comment by colepatrickturner** [comment]
Fantastic! Please add your name to the credits and will merge/push :)

**Comment by jschwertfeger** [comment]
Ready for merging. Choose the squashing option while merging so my two commits are merged into one, if you like.

**Comment by colepatrickturner** [comment]
Merged and pushed. Thanks again!

**Comment by jschwertfeger** [comment]
You're welcome. I just opened another PR.

**Pull request merged**
